#!/bin/bash
#!/bin/bash
if [ ! -r "conf/compose.env" ]
then
    echo "Error: Missing conf/compose.env."
    echo "       Please copy and edit from conf/compose.env.tpl."
    exit 1
fi
source conf/compose.env

action=${1:-''}

echo_y () {
    echo -e "\033[1;33m$@\033[0m"
}

do_start () {
    echo_y "Starting docker-lamop..."
    bin/compose up -d
    echo_y "docker-lamop is running."
}

do_fullstart () {
    echo_y "Building required images ..."
    bin/compose build
    echo_y "Build done."
    do_start
}

do_stop () {
    echo_y "Stopping docker-lamop ..."
    bin/compose stop
    echo_y "docker-lamop is stopped."
}

do_status () {
    bin/compose ps
}

do_console() {
    docker exec -u www-data -it ${COMPOSE_PROJECT_NAME}_php_1 bash -c 'cd /var/www; exec "bash";'
}

case "$action" in
    fullstart)
        do_fullstart
        ;;
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    console)
        do_console
        ;;
    status)
        do_status
        ;;
    *)
        echo "usage: $0 [start|fullstart|stop|status|console]"
        exit 1
        ;;
esac
