#!/usr/bin/python3
from argparse import ArgumentParser
from configparser import ConfigParser
import subprocess
import os
import sys


MAIN_CONFIGURATION_FILE = 'conf/compose.ini'

class Lamp():
    def read_mainconf_or_exit(self):
        """Check if the configuration file exists"""
        if os.path.isfile(MAIN_CONFIGURATION_FILE) is False:
            msg = 'Error: Missing ' + MAIN_CONFIGURATION_FILE + ' '
            msg += 'Create it and override values from ' + MAIN_CONFIGURATION_FILE + '.tpl'
            raise IOError(msg)

        self.config = self.__parse_config()

    def get_action(self):
        arg_parser = ArgumentParser(description="Process the only argument expected (The action)")
        arg_parser.add_argument('action', help='Command for lamp', nargs='?')
        args = arg_parser.parse_args()

        return args.action

    def call_the_right_function(self, action: str):
        switcher = {
            'start': self.__do_start,
            'stop': self.__do_stop,
            'fullstart': self.__do_fullstart,
            'status': self.__do_status,
            'run-php': self.__do_run_php,
            'console': self.__do_console
        }
        switcher.get(action, self.__do_usage)()


    def __parse_config(self):
        config = ConfigParser()
        config.read(MAIN_CONFIGURATION_FILE)
        return config

    def __do_usage(self):
        print('usage: ./' + os.path.basename(__file__) + ' [start|fullstart|stop|status|console]')
        sys.exit(1)

    def __do_start(self):
        self.__print_colored('Starting ' + os.path.basename(__file__)  + '..')
        subprocess.run(['bin/compose.py', 'up'])
        self.__print_colored(os.path.basename(__file__)  + ' is running')

    def __do_fullstart(self):
        self.__print_colored("Building required images ...")
        subprocess.run(['bin/compose.py', 'build'])
        self.__print_colored("Build done.")
        self.__do_start()

    def __do_stop(self):
        self.__print_colored("Stopping docker-lamop ...")
        subprocess.run(['bin/compose.py', 'stop'])
        self.__print_colored("docker-lamop is stopped.")

    def __do_status(self):
        subprocess.run(['bin/compose.py', 'ps'])

    def __do_console(self):
        subprocess.run(['docker', 'exec', '-u', 'www-data', '-it', self.__get_php_vm_name(), 'bash'])

    def __do_run_php(self):
        cmd = ['docker', 'exec', '-u', 'www-data', '-t', '-i', self.__get_php_vm_name()]
        cmd += ['bash', '-c', '-- "cd /var; /usr/bin/php -v"']
        subprocess.run()

    def __print_colored(self, string: str):
        print('\033[1;33m' + string + '\033[0m')

    def __get_php_vm_name(self):
        project_name = self.config['main'].get('project_name', 'inet' + os.path.basename(os.getcwd()).replace('-', ''))
        return project_name + '_php_1'


if __name__ == '__main__':
    try:
        lamp = Lamp()
        lamp.read_mainconf_or_exit()
        lamp.call_the_right_function(lamp.get_action())
    except Exception as e:
        msg =  r"""
              ______ _____  _____   ____  _____
             |  ____|  __ \|  __ \ / __ \|  __ \
             | |__  | |__) | |__) | |  | | |__) |
             |  __| |  _  /|  _  /| |  | |  _  /
             | |____| | \ \| | \ \| |__| | | \ \
             |______|_|  \_\_|  \_\\____/|_|  \_\

"""

        msg += '\033[1;31m' + str(e) + '\033[0m'

        print(msg)
        exit(1)
