version: '2.2'

services:
    nginx:
        image: edyan/nginx:${DOCKER_NGINX_VERSION}
        mem_limit: ${DOCKER_NGINX_RAM}
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        hostname: ${COMPOSE_PROJECT_NAME}_nginx
        networks: [stakkr]
        environment:
            NGINX_UID: ${DOCKER_UID}
            NGINX_GID: ${DOCKER_GID}
            NGINX_DOCUMENT_ROOT: ${DOCKER_NGINX_DOCUMENT_ROOT}
        volumes:
            - ${COMPOSE_BASE_DIR}/home/www-data:/home/www-data
            - ${COMPOSE_BASE_DIR}/logs/nginx:/var/log/nginx
            - ${COMPOSE_BASE_DIR}/www:/var/www
        labels:
            - traefik.frontend.rule=Host:nginx.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}
