version: "3.8"

# See also https://github.com/francescou/docker-compose-ui
services:
  portainer:
    image: portainer/portainer:${DOCKER_PORTAINER_VERSION}
    mem_limit: ${DOCKER_PORTAINER_RAM}
    container_name: ${COMPOSE_PROJECT_NAME}_portainer
    hostname: ${COMPOSE_PROJECT_NAME}_portainer
    networks: [stakkr]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${COMPOSE_BASE_DIR}/data/portainer:/data
    command: ['--no-analytics']
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.tls: "true"
      traefik.http.routers.portainer.rule: "Host(`portainer.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}`)"
      traefik.http.services.portainer.loadbalancer.server.port: 9000
