version: '2.2'

services:
    redis:
        image: redis:${DOCKER_REDIS_VERSION}
        mem_limit: ${DOCKER_REDIS_RAM}
        container_name: ${COMPOSE_PROJECT_NAME}_redis
        hostname: ${COMPOSE_PROJECT_NAME}_redis
        networks: [stakkr]
        volumes:
            - ${COMPOSE_BASE_DIR}/data/redis:/var/lib/redis
